apiVersion: v1
kind: Service
metadata:
  name: octavia-small-to-upgrade
  annotations:
    loadbalancer.ovhcloud.com/class: "octavia"
    # Default flavor is small
  labels:
    app: test-octavia
spec:
  ports:
  - name: client
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
